name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Publish on Modrinth
          modrinth-id: toTeYMOI
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-name: Disconnect Packet Fix - Neoforge

          # Publish on GitHub.
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: build/libs/*.jar
